name: UTC App  CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
    python_version: 3.11
    IMAGE_NAME: portfolio
    AWS_REGION: us-east-1
    ACCOUNT_ID: ${{secrets.ACCOUNT_ID}}
    ECR_REPO: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: python set up
              uses: actions/setup-python@v4
              with: 
                  python-version: ${{env.python_version}}
            - name: Instal pytest
              run: pip install -r requirements.txt
            - name: unit test
              run: pytest test.py
            - name: Configure AWS credentials using OIDC
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{secrets.ROLE_ARN}}
                aws-region: ${{env.AWS_REGION}}
            - name: Build image
              run: docker build -t ywet/my-portfolio_2 .

            - name: Check credentials
              run: aws s3 ls





