name: UTC App  CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read
env:
    python_version: 3.11
    IMAGE_NAME: portfolio
    AWS_REGION: us-east-1
    ACOUNT_ID: ${{secrets.ACOUNT_ID}}
    ECR_REPO: $ACOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: python set up
              uses: actions/setup-python@v4
              with:  
                python-version: ${{ env.python_version }}
            - name: Install pytest
              run: pip install -r requirements.txt
            - name: unit test
              run: pytest test.py
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Configure AWS credentials using OIDC
              uses: aws-actions/configure-aws-credentials@v2
              with:
                role-to-assume: ${{ secrets.ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}
            - name: running some tests
              run: aws s3 ls

